source 'http://rubygems.org'

gem 'sinatra', '~> 1.1.2'
gem 'excon', '~> 0.4.0'
gem 'nokogiri', '~> 1.4.4'
gem 'activesupport', '~> 3.0.3'
gem 'i18n'
gem 'dalli', '~> 1.0.1'
gem 'builder', '~> 3.0.0'
gem 'mongrel'